# Generated by Django 5.1.7 on 2025-03-27 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_analyze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
