# Generated by Django 5.1.7 on 2025-03-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_analyze', '0002_imageupload_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='hash',
            field=models.CharField(default='7ad70f36-09ca-4089-a97c-6d93303cde5e', max_length=255),
        ),
    ]
