# Generated by Django 5.1.7 on 2025-03-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_analyze', '0003_alter_imageupload_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='hash',
            field=models.CharField(default='87996245-e871-4c22-9cb7-d06b171b3e71', max_length=255, unique=True),
        ),
    ]
