# Generated by Django 5.1.7 on 2025-03-27 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_analyze', '0004_alter_imageupload_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='hash',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
